# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
    - blog
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules

# tarvis生命周期执行顺序详见官网文档
before_install:
  - git config --global user.name "xiyusullos"
  - git config --global user.email "i@xy-jit.cc"
  # 由于使用了yarn，所以需要下载，如不用yarn这两行可以删除
  # - curl -o- -L https://yarnpkg.com/install.sh | bash
  # - export PATH=$HOME/.yarn/bin:$PATH
  - npm install -g hexo-cli

install:
  # 不用yarn的话这里改成 npm i 即可
  # - yarn
  npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "xiyusullos"
  - git config user.email "i@xy-jit.cc"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  # GH_TOKEN是在Travis中配置token的名称

env:
  global:
    - GH_REF: github.com/xiyusullos/xiyusullos.github.io.git  # 设置GH_REF